language: rust
sudo: false
# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # optional: only required for the --verify flag of coveralls
cache: cargo

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
    - os: osx

os:
  - linux
  - osx

# load travis-cargo
before_script:
  - pip install 'travis-cargo<0.2' --user
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$HOME/.local/bin:$PATH; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then export PATH=$HOME/Library/Python/2.7/bin:$PATH; fi
  # Install OpenSSL through homebrew
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew update && brew install openssl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then export LDFLAGS='-L/usr/local/opt/openssl/lib'; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then export CPPFLAGS='-I/usr/local/opt/openssl/include'; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then export PKG_CONFIG_PATH='/usr/local/opt/openssl/lib/pkgconfig'; fi


# the main build
script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only stable doc

after_success:
  # upload the documentation from the build with stable (automatically only actually
  # runs on the master branch, not individual PRs)
  # - travis-cargo --only stable doc-upload
  # measure code coverage and upload to coveralls.io (the verify
  # argument mitigates kcov crashes due to malformed debuginfo, at the
  # cost of some speed <https://github.com/huonw/travis-cargo/issues/12>)
  # - travis-cargo coveralls --no-sudo --verify
  # https://github.com/huonw/travis-cargo/issues/58
  # See https://github.com/ujh/iomrascalai/blob/master/.travis.yml
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis-cargo coveralls --no-sudo --verify; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./kcov/build/src/kcov --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/gitlab_api-*; fi
