[package]
name = "gitlab-api"
version = "0.1.0"
authors = ["Nicolas Bigaouette <nbigaouette@gmail.com>"]

[dependencies]
hyper = { version = "0.9", default-features = false, features = ["security-framework"] }
